version: "3.7"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo/db:/data/db
    ports:
      - 27017:27017
    restart: always

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    restart: always
  
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
    restart: always
    
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
  
  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  nifi-file-reader:
    image: 'apache/nifi:1.12.1'
    container_name: nifi-file-reader
    ports:
      - "8080:8080"
    volumes:
      - ./nifi_file/input:/opt/nifi/nifi-current/input
    depends_on:
      - "kafka-1"
      - "kafka-2"
      - "mongodb"
    restart: always

  nifi-kafka-consumer:
    image: 'apache/nifi:1.12.1'
    container_name: nifi-kafka-consumer
    ports:
      - "9090:8080"
    depends_on:
      - "kafka-1"
      - "kafka-2"
      - "mongodb"
    restart: always

  nifi-registry:
    image: michalklempa/nifi-registry
    container_name: nifi-registry
    volumes:
      - "/home/italo/.ssh:/home/nifi/.ssh"
    ports:
      - target: 18080
        published: 18080
        protocol: tcp
        mode: host
    environment:
      DEBUG: 1
      FLOW_PROVIDER: git
      GIT_REMOTE_URL: git@github.com:imacellone/nifi-registry.git
      GIT_CHECKOUT_BRANCH: master
      FLOW_PROVIDER_GIT_FLOW_STORAGE_DIRECTORY: /opt/nifi-registry/flow-storage-git
      FLOW_PROVIDER_GIT_REMOTE_TO_PUSH: origin
      GIT_CONFIG_USER_NAME: 'Italo Macellone' # Substitua com o seu próprio nome.
      GIT_CONFIG_USER_EMAIL: italomacellone@gmail.com # Substitua com o seu próprio e-mail.
    restart: always